In [21]:
import keras
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
from keras.layers.convolutional import Convolution2D,MaxPooling2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [22]:
data=pd.read_csv('mnist_train.csv')
print(data.head())

   label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]


In [23]:
data

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [25]:
r=data.iloc[3,1:].values.reshape(28,28).astype('uint8')
print(r)


[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  124 253 255  63   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  96
  244 251 253  62   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 127
  251 251 253  62   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

In [26]:
df_x=data.iloc[:,1:].values.reshape(len(data),28,28,1)
y=data.iloc[:,0].values
print(y)


[5 0 4 ... 5 6 8]


In [27]:
#converting lebel to categorical class
df_y=keras.utils.to_categorical(y,num_classes=10)


In [28]:
df_x=np.array(df_x)
df_y=np.array(df_y)
print(df_y)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [29]:
print(df_y.shape)

(60000, 10)


In [30]:
x_train,x_test,y_train,y_test=  train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [31]:
model=Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [32]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 100)               540900    
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1010      
Total params: 542,230
Trainable params: 542,230
Non-trainable params: 0
________________________________________________

In [33]:
#for fitting it just 100 images for testing 
model.fit(x_train[1:100],y_train[1:100],validation_data=(x_test[1:20],y_test[1:20]))


Train on 99 samples, validate on 19 samples
Epoch 1/1
99/99 [==============================] - 2s 18ms/step - loss: 8.0543 - accuracy: 0.1212 - val_loss: 9.7214 - val_accuracy: 0.0526


In [34]:
model.predict(x_test[1:20])

array([[-165.86537  ,  -51.373188 ,  -35.704475 ,   35.56493  ,
         113.14151  ,  -39.20662  ,  297.13156  , -488.8234   ,
          64.302025 ,   41.815422 ],
       [-340.46536  , -111.535965 ,  -58.091614 ,   66.78939  ,
          96.79119  ,  -21.431252 ,  479.8986   , -415.1607   ,
          86.222046 ,  101.22072  ],
       [ -79.76481  ,  -10.649194 ,  -10.997739 ,  -35.018772 ,
          28.602755 ,  -17.075653 ,  119.14559  , -185.94052  ,
          16.791853 ,   -0.8061989],
       [-252.42972  ,  -18.43837  , -129.37155  ,  -22.700954 ,
         101.758194 ,  -69.047035 ,  340.30054  , -468.89178  ,
         160.69287  ,   45.276985 ],
       [-333.68994  ,   -6.1826406, -115.0154   ,   73.0524   ,
          81.762146 ,   96.93983  ,  506.06326  , -419.6181   ,
         241.92766  ,   67.81194  ],
       [-318.3131   ,  -72.935425 , -134.35547  ,   77.21194  ,
         103.02085  ,   11.926782 ,  473.71167  , -413.0182   ,
         194.07953  ,   82.130775 ],
       [-1